### ISSUE TITLE
Local Interface Not Listed

### ISSUE THREAD

**Issue by rcrdcanepa** [PackeTsar/neighbor-parser#9] opened 2023-05-09 19:16 UTC
**Describe The Bug**
I noticed that on the Cisco IOS XR Software, Version 6.7.3, the Local Interface (short of not) does not get listed.

**Sanitized Neighbor Output**

```
I prefer not to paste the output.
```
Thank you for this interesting tool.

**Comment by PackeTsar** [comment] 2023-05-09 19:29
Any way you can sanitize the output and paste it in? I need an example of the output so I can reproduce and fix the issue.

**Comment by rcrdcanepa** [comment] 2023-05-09 20:10
Here it is:
!
!
-------------------------
Device ID: SW1
SysName : 
Entry address(es): 
  IPv4 address: 10.10.20.11
Platform: cisco WS-C3560X-24,  Capabilities: Switch IGMP 
Interface: MgmtEth0/RSP0/CPU0/0
Port ID (outgoing port): GigabitEthernet0/9
Holdtime : 169 sec

Version :
Cisco IOS Software, C3560E Software (C3560E-UNIVERSALK9-M), Version 15.0(2)SE7, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2014 by Cisco Systems, Inc.
Compiled Thu 23-Oct-14 13:27 by prod_rel_team

advertisement version: 2
Protocol Hello:  OUI=0x00000C, Protocol ID=0x0112; payload len=27, value=00000000FFFFFFFF010221FF000000000000ACF2C58A8E00FF00004A0011C000
VTP Management Domain: 'TTT'
Native VLAN: 1700
Duplex: full

-------------------------
Device ID: SW2
SysName : 
Entry address(es): 
  IPv4 address: 10.10.30.12
Platform: cisco WS-C4500X-16,  Capabilities: Router Switch IGMP 
Interface: TenGigE0/0/1/0
Port ID (outgoing port): TenGigabitEthernet1/1
Holdtime : 169 sec

Version :
Cisco IOS Software, Catalyst 4500 L3 Switch Software (cat4500e-UNIVERSALK9-M), Version 15.1(2)SG5, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2014 by Cisco Systems, Inc.
Compiled Mon 03-Nov-14 09:05 by prod_rel_team

advertisement version: 2
Native VLAN: 1
Duplex: full

-------------------------
Device ID: RT1
SysName : RT1
Entry address(es): 
  IPv4 address: 10.10.30.12
Platform: cisco ASR9K Series,  Capabilities: Router 
Interface: TenGigE0/0/1/1
Port ID (outgoing port): TenGigE0/0/2/0
Holdtime : 144 sec

Version :
Cisco IOS XR Software, Version 6.1.4[Default]
Copyright (c) 2017 by Cisco Systems, Inc.

advertisement version: 2
Duplex: full

-------------------------
Device ID: SW4
SysName : SW4
Entry address(es): 
  IPv4 address: 10.10.50.37
Platform: N9K-C93180YC-EX,  Capabilities: Router Switch IGMP 
Interface: TenGigE0/0/1/2
Port ID (outgoing port): Ethernet1/40
Holdtime : 135 sec

Version :
Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I7(3)

advertisement version: 2
Native VLAN: 1
Duplex: full

-------------------------
Device ID: SW5
SysName : 
Entry address(es): 
  IPv4 address: 10.10.30.65
Platform: cisco WS-C4948E,  Capabilities: Router Switch IGMP 
Interface: TenGigE0/0/1/3
Port ID (outgoing port): TenGigabitEthernet1/49
Holdtime : 136 sec

Version :
Cisco IOS Software, Catalyst 4500 L3 Switch  Software (cat4500e-ENTSERVICESK9-M), Version 15.2(2)E, RELEASE SOFTWARE (fc3)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2014 by Cisco Systems, Inc.
Compiled Thu 26-Jun-14 13:51 by prod_rel_team

advertisement version: 2
Native VLAN: 1
Duplex: full

-------------------------
Device ID: SW6
SysName : 
Entry address(es): 
  IPv4 address: 10.10.10.132
Platform: cisco WS-C3750G-48TS,  Capabilities: Switch IGMP 
Interface: GigabitEthernet0/0/0/2
Port ID (outgoing port): GigabitEthernet1/0/2
Holdtime : 176 sec

Version :
Cisco IOS Software, C3750 Software (C3750-IPSERVICESK9-M), Version 15.0(1)SE3, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2012 by Cisco Systems, Inc.
Compiled Wed 30-May-12 14:10 by prod_rel_team

advertisement version: 2
Protocol Hello:  OUI=0x00000C, Protocol ID=0x0112; payload len=27, value=00000000FFFFFFFF010221FF0000000000006C9CED997400FF0000FEB0002BF3
VTP Management Domain: 'TTT'
Native VLAN: 1
Duplex: full

-------------------------
Device ID: SW6
SysName : 
Entry address(es): 
  IPv4 address: 10.10.10.132
Platform: cisco WS-C3750G-48TS,  Capabilities: Switch IGMP 
Interface: GigabitEthernet0/0/0/3
Port ID (outgoing port): GigabitEthernet2/0/1
Holdtime : 176 sec

Version :
Cisco IOS Software, C3750 Software (C3750-IPSERVICESK9-M), Version 15.0(1)SE3, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2012 by Cisco Systems, Inc.
Compiled Wed 30-May-12 14:10 by prod_rel_team

advertisement version: 2
Protocol Hello:  OUI=0x00000C, Protocol ID=0x0112; payload len=27, value=00000000FFFFFFFF010221FF0000000000006C9CED997400FF0000FE84002BF3
VTP Management Domain: 'TTT'
Native VLAN: 1
Duplex: full

-------------------------
Device ID: SW7
SysName : SW7
Entry address(es): 
  IPv4 address: 10.10.40.15
Platform: N3K-C3064PQ-10GE,  Capabilities: Router Switch IGMP 
Interface: GigabitEthernet0/0/0/7
Port ID (outgoing port): Ethernet1/1
Holdtime : 152 sec
Version :
Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I7(6)

advertisement version: 2
Native VLAN: 1
Duplex: full

-------------------------
Device ID: SW8
SysName : SW8
Entry address(es): 
  IPv4 address: 10.10.10.53
Platform: N9K-C93180YC-EX,  Capabilities: Router Switch IGMP 
Interface: GigabitEthernet0/0/0/14
Port ID (outgoing port): Ethernet1/38
Holdtime : 136 sec

Version :
Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I4(2)

advertisement version: 2
Native VLAN: 1
Duplex: full

-------------------------
Device ID: SW9
SysName : 
Entry address(es): 
  IPv4 address: 10.10.10.221
Platform: cisco C9300-48T,  Capabilities: Router Switch IGMP 
Interface: GigabitEthernet0/0/0/15
Port ID (outgoing port): GigabitEthernet1/0/1
Holdtime : 161 sec

Version :
Cisco IOS Software [Fuji], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 16.9.5, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2020 by Cisco Systems, Inc.
Compiled Thu 30-Jan-20 18:53 by mcpre

advertisement version: 2
VTP Management Domain: 'TTT'
Native VLAN: 1
Duplex: full
          
-------------------------
Device ID: RT4
SysName : RT4
Entry address(es): 
  IPv4 address: 10.10.10.15
Platform: cisco ASR9K Series,  Capabilities: Router 
Interface: TenGigE0/0/2/3
Port ID (outgoing port): TenGigE0/0/2/3
Holdtime : 121 sec

Version :
Cisco IOS XR Software, Version 6.7.3[Default]
Copyright (c) 2020 by Cisco Systems, Inc.

advertisement version: 2
Duplex: full
!
!
Thanks,

**Comment by PackeTsar** [comment] 2023-05-09 21:25
This should be fixed in v1.5.1. Looks like other OS's put the local and remote interface on the same line whereas IOS-XR lists them on different lines. Thanks for providing the example so I could get it fixed.

New version is deploying now so you should see it live momentarily

**Comment by PackeTsar** [comment] 2023-05-09 21:26
I'm opening the case back up so you can confirm things look good now

**Comment by rcrdcanepa** [comment] 2023-05-10 00:03
Thank you.

**Comment by rcrdcanepa** [comment] 2023-05-10 00:08
I just confirmed that it is working on version v1.5.1.
Thanks again!

**Closed as completed** 2023-05-10 01:50 UTC
